import Link from "next/link";
import { Card } from "@/components/ui/card";
import { FarmtryBrand } from "./farmtry-brand";
import { LandingHeader } from "./landing-header";

const base = "/figma/landing/";
function Icon({ file }: { file: string }) { return <img className="farmtry-icon" src={base + file} alt="" />; }
function Arrow() { return <Icon file="95d1b.svg" />; }

function FeaturePhone() {
  return <div className="farmtry-phone" aria-label="Illustration of Farmtry SMS notifications, showing example data">
    <div className="farmtry-phone-speaker" /><div className="farmtry-phone-brand"><strong>FARMTRY 2G COMM</strong><span><Icon file="1ca05.svg" /> MTN NG <Icon file="ac192.svg" /></span></div>
    <div className="farmtry-phone-screen"><div className="farmtry-sms"><div className="farmtry-sms-heading"><span>SMS: FARMTRY</span><span>10:42 AM</span></div><p><strong>FARMTRY:</strong> Cassava Peel (120kg) verified at Hub! <strong>₦14,400</strong> credited directly to your account.</p><strong className="farmtry-sms-success">Instant cash payout completed.</strong></div><div className="farmtry-sms farmtry-sms-outgoing"><div className="farmtry-sms-heading"><span>You (Farmer)</span><span>10:45 AM</span></div><strong>BAL</strong></div><div className="farmtry-sms"><div className="farmtry-sms-heading"><span>SMS: FARMTRY</span><span>10:45 AM</span></div><p>Account Balance: <strong>₦50,700</strong>.</p><small>All produce &amp; waste earnings paid directly to your registered bank / mobile wallet.<br />Text CASH to withdraw.</small></div></div>
    <div className="farmtry-phone-keypad" aria-hidden="true"><div className="farmtry-phone-controls"><i /><b>●</b><i /></div><div className="farmtry-keys">{["1", "2|ABC", "3|DEF", "4|GHI", "5|JKL", "6|MNO"].map(key => <span key={key}>{key.split("|")[0]}<small>{key.split("|")[1] || "\u00a0"}</small></span>)}</div></div>
    <div className="farmtry-phone-caption"><Icon file="b29f1.svg" /><span>Works on basic 2G feature phones via SMS<br />&amp; USSD — zero data required</span></div>
  </div>;
}

const pillars = [
  { id: "farmers", title: "For Smallholder Farmers", icon: "373db.svg", description: "Fair gate prices, no post-harvest waste, and steady access to inputs for growth.", features: [["d2324.svg", "Transparent fair prices: Updated live and tied to market rates."], ["422dd.svg", "Agro-waste value: Turn peels, husks, and cobs into something useful instead of throwing them away."]], link: "Learn Farmtry Engine", href: "/#settlement" },
  { id: "aggregators", title: "For Field Aggregators", icon: "45a4f.svg", description: "Turn local sourcing relationships into guaranteed contracts without tying up cash.", features: [["d050f.svg", "Guaranteed buyer matches: fixed purchase contracts from verified processors."], ["8e6f7.svg", "Automated commissions: fixed aggregator margins paid immediately after batch clearance."], ["80175.svg", "Digital Collection Tickets: Paperless farmer intake using Bluetooth scale data."]], link: "Join Aggregator Network", href: "/preview/aggregator-register" },
  { id: "buyers", title: "For Corporate Buyers", icon: "1c223.svg", description: "Keep supply steady with verified volumes and secure payments.", features: [["7578d.svg", "Tested standards: strict quality checks backed by digital certificates."], ["2e27b.svg", "Automated GRN: Instant goods received note triggered by digital scale and weighbridge checks."], ["c8580.svg", "Guaranteed Direct Settlement: Capital is paid securely once offloading meets the agreed specs."]], link: "Register as a buyer", href: "/preview/buyer-register" }
];

export function LandingPage() {
  return <div className="farmtry-site"><LandingHeader /><main id="main-content">
    <section className="farmtry-hero"><div className="farmtry-container"><div className="farmtry-hero-grid"><div className="farmtry-hero-copy"><span className="farmtry-pill"><i /> THE SMS-TO-MARKET PLATFORM</span><h1>Turning every<br className="farmtry-desktop-break" /> farmer’s phone into<br className="farmtry-desktop-break" /> a <span>full-stack<br className="farmtry-desktop-break" /> marketplace.</span></h1><p>No smartphone. No internet. No middleman. Connecting rural farmers, aggregators, dealers, and corporate buyers across Nigeria’s agricultural value chain.</p><div className="farmtry-hero-actions"><Link className="farmtry-action" href="/preview/marketplace">🛒 Explore Public Marketplace</Link><a className="farmtry-action farmtry-action-outline" href="#gateways">🏢 Enterprise Gateways</a></div><ul className="farmtry-feature-badges">{["Guaranteed Settlement Rails", "Zero Data & 2G USSD Compatible", "FIRS WHT Automated Clearance"].map(text => <li key={text}><Icon file="c07ca.svg" />{text}</li>)}</ul></div><FeaturePhone /></div>
    <div className="farmtry-metrics">{[["7d749.svg", "POST-HARVEST SHIELD", "40–50%", "Post-harvest loss eliminated for matched produce"], ["4df61.svg", "INCLUSIVE REACH", "60M+", "Smallholder farmers reachable via basic SMS"], ["1c346.svg", "DIRECT FARMER PAYOUT", "100%", "Instant cash settlement for all produce & agro-waste"], ["9b6d1.svg", "CLEARED VOLUME", "₦4.2B+", "Direct trade settled"]].map(([icon, label, value, detail]) => <Card className="farmtry-metric" key={label}><div><Icon file={icon} /><span>{label}</span></div><strong>{value}</strong><p>{detail}</p></Card>)}</div></div></section>
    <section id="gateways" className="farmtry-gateways farmtry-container"><div className="farmtry-section-heading"><span className="farmtry-pill"><Icon file="65f51.svg" /> INSTITUTIONAL ROLE GATEWAYS</span><h2>Enterprise Gateway</h2><p>Secure login for corporate buyers and aggregator</p></div><div className="farmtry-gateway-grid">{[
      { emoji: "🏭", badge: "Buyer Gateway", title: "Corporate Buyer Hub", description: "Enterprise grade procurement suite for feed mills, FMCG food processors, and export commodities off-takers.", features: ["Automated Digital Goods Received Notes (GRN)", "Lab certificate vault for moisture, aflatoxin, and grade checks", "Multi-user approval steps for purchases"], signIn: "Sign in as Corporate Buyer", register: "Register New Enterprise Account", route: "buyer" },
      { emoji: "🚚", badge: "Aggregator Gateway", title: "Aggregator Hub", description: "Dedicated operating system for field collection agents, local coordinators, and off-grid weighing station operators.", features: ["Digital intake logs synced to Bluetooth weighbridges", "Real-time commission payouts upon batch clearance", "Farmer cluster onboarding & offline SMS dispatch tools"], signIn: "Sign in to Aggregator Hub", register: "Register as New Field Agent", route: "aggregator" }
    ].map(gateway => <Card className="farmtry-gateway" key={gateway.route}><div className="farmtry-gateway-top"><span>{gateway.emoji}</span><small>{gateway.badge}</small></div><h3>{gateway.title}</h3><p>{gateway.description}</p><ul>{gateway.features.map(feature => <li key={feature}><Icon file="def70.svg" />{feature}</li>)}</ul><div className="farmtry-gateway-links"><Link className="farmtry-action" href={`/preview/${gateway.route}-login`}>{gateway.signIn} →</Link><Link href={`/preview/${gateway.route}-register`}>{gateway.register} →</Link></div></Card>)}</div></section>
    <section className="farmtry-ecosystem farmtry-container"><div className="farmtry-section-row"><div><p className="farmtry-eyebrow">ECOSYSTEM ARCHITECTURE</p><h2>The 3-Way Value Model</h2></div><p>Making Nigerian farm supply chains fairer, safer,<br /> and less wasteful.</p></div><div className="farmtry-pillar-grid">{pillars.map((pillar, index) => <Card className="farmtry-pillar" key={pillar.id}><div id={pillar.id} className="farmtry-pillar-icon"><Icon file={pillar.icon} /></div><p className="farmtry-eyebrow">STAKEHOLDER PILLAR 0{index + 1}</p><h3>{pillar.title}</h3><p className="farmtry-pillar-description">{pillar.description}</p><ul>{pillar.features.map(([icon, text]) => <li key={icon}><Icon file={icon} /><span>{text}</span></li>)}</ul><Link className="farmtry-text-link" href={pillar.href}>{pillar.link}<Arrow /></Link></Card>)}</div></section>
    <section className="farmtry-marketplace farmtry-container"><div className="farmtry-section-row"><div><span className="farmtry-pill">MARKETPLACE</span><h2>Verified Agri Products Ready for Off-Take</h2></div><Link className="farmtry-text-link" href="/preview/marketplace">Browse All Products <Icon file="71c28.svg" /></Link></div><p className="farmtry-preview-label">Design preview · Availability and prices are illustrative.</p><div className="farmtry-product-grid">{[false, false, true].map((fresh, index) => <Card className={`farmtry-product ${fresh ? "farmtry-product-fresh" : ""}`} key={index}><div className="farmtry-product-image"><img src={base + (fresh ? "5f69b.png" : "04f79.png")} alt={fresh ? "Fresh tomatoes at a produce market" : "Sun-dried cassava peels"} /><span><Icon file={fresh ? "62386.svg" : "89863.svg"} />{fresh ? "Fresh Produce" : "Farm Waste"}</span><small>{fresh ? "Fast Transit SLA" : "Grade A Industrial"}</small></div><div className="farmtry-product-content"><div className="farmtry-product-meta"><span>Lot #{fresh ? "TM-4410" : "CS-8924"}</span><span>{fresh ? "Kaduna Central" : "Oyo Central Hub"}</span></div><h3>{fresh ? "Tomatoes" : "Sun-Dried Cassava Peels"}</h3><div className="farmtry-product-price"><div><span>Available Volume</span><strong>{fresh ? "3,200" : "12,000"} <small>kg</small></strong></div><div><span>Spot Unit Price</span><strong>{fresh ? "₦310" : "₦18"} <small>/ kg</small></strong></div></div><Link className="farmtry-action" href="/preview/product">Buy Now</Link></div></Card>)}</div></section>
    <section id="settlement" className="farmtry-settlement farmtry-container"><div className="farmtry-settlement-panel"><span className="farmtry-pill"><Icon file="08c8a.svg" /> INSTITUTIONAL GRADE SETTLEMENT</span><h2>Statutory<br /> Transparency &amp; Bank-<br />Grade Direct<br /> Settlement</h2><p>We eliminate payment risk with secure, CBN-compliant settlement.<br />Payment is released only after digital scale checks and quality approval.</p><div className="farmtry-settlement-steps">{[["Direct Trade Funded", "Buyer pays into a verified farmtry account before dispatch."], ["Transit & Tracking", "Orders tracked by location checks, weighbridge records, and moisture seals."], ["QR GRN Sign-Off", "Factory scans QR and split payments between aggregators and farmers."]].map(([title, detail], index) => <Card className="farmtry-settlement-step" key={title}><span>{index + 1}</span><h3>{title}</h3><p>{detail}</p></Card>)}</div></div></section>
    <section className="farmtry-final-cta farmtry-container"><div><div><h2>Ready to Streamline Your<br />Agricultural Supply Chain?</h2><p>Connect your factory or feed mill to over 1,420 hubs<br /> across Nigeria with direct settlement and clear grading.</p></div><Link className="farmtry-action" href="/preview/buyer-register">Register As a Corporate Buyer</Link></div></section>
  </main><footer className="farmtry-footer"><div className="farmtry-container"><div className="farmtry-footer-grid"><div><FarmtryBrand /><p>We help businesses buy farm goods, turn organic waste into value, and settle payments securely across growing farming areas.</p><span className="farmtry-accredited"><Icon file="307cf.svg" /> CAC Accredited</span></div><div><h3>ENTERPRISE</h3><Link href="/preview/buyer">Corporate Buyer Suite</Link><Link href="/preview/aggregator">Aggregator Hub</Link><Link href="/preview/marketplace">Agri Waste Exchange</Link><a href="#settlement">Guaranteed Settlement</a></div><div><h3>GOVERNANCE &amp; TRUST</h3>{["FIRS & CAC Verification", "Quality Grading Standards", "Master Service Agreement", "Data Protection Policy"].map(label => <Link href="/preview/governance" key={label}>{label}</Link>)}</div><div><h3>SUPPORT &amp; DESK</h3><Link href="/preview/support">Aggregator Help Center</Link><Link href="/preview/support">Disputes</Link></div></div><p className="farmtry-copyright">© 2025 Farmtry Agrisystems Limited. Fully incorporated under CAC RC: 1892044. All rights reserved.</p></div></footer></div>;
}
