"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FarmtryBrand } from "@/features/landing/components/farmtry-brand";
export function AdminAuth({screen,initialMethod="email"}:{screen:"login"|"recovery"|"reset";initialMethod?:"email"|"sms"}){
  const [method,setMethod]=useState(initialMethod),[visible,setVisible]=useState(false),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[code,setCode]=useState(""),[notice,setNotice]=useState("");
  const login=screen==="login",reset=screen==="reset";const features=login?["View Platform Analytics","Manage Users & Roles","Monitor Transactions","System Settings"]:reset?["Minimum 8 characters","Alphanumeric & special symbols","Account access protection","Secure recovery"]:["Two-Factor Verification","Encrypted Recovery Tokens","SMS & Email Recovery","Account Access Security"];
  const icons=login?[19100,19106,19112,19118]:reset?[19494,19500,19506,19512]:[19637,19643,19649,19655];const source=login?"383-19072":reset?"383-19472":"383-19617";
  return <main className="admin-auth"><div className="admin-auth-layout"><aside className="admin-auth-story"><FarmtryBrand/><p className="admin-auth-role">ADMIN PORTAL</p><h1>{login?<>Welcome back,<br/><em>Admin.</em></>:reset?<>Set a new<br/><em>secure password.</em></>:<>Account Recovery &amp;<br/><em>Access Security.</em></>}</h1><p>{login?"Access your dashboard, manage users, monitor activities and keep the platform running smoothly.":reset?"Protect your agricultural trade transactions, orders, and company profile with a secure password.":"Recover access to administrative accounts across our agricultural supply chain."}</p><ul>{features.map((f,i)=><li key={f}><img src={`/figma/admin/${source}/383-${icons[i]}.svg`} alt=""/>{f}</li>)}</ul>{login?<img className="admin-auth-portrait" src="/figma/admin/383-19072/383-19079.svg" alt="Administrator monitoring analytics on a laptop"/>:!reset?<img className="admin-auth-recovery-image" src="/figma/admin/383-19617/383-19661.svg" alt="Agricultural logistics operations"/>:null}<p className="admin-auth-foot">Secure · Trusted · Efficient</p></aside><section className="admin-auth-panel"><Link href={login?"/":"/preview/admin-login/"}>← Back to {login?"Home":"Login"}</Link><div className="admin-auth-form-wrap"><h2>{login?"Admin Login":reset?"Reset Password":"Forgot Password?"}</h2><p>{login?"Enter your details to access the admin portal.":reset?"Enter a recovery code and choose your new password.":"Choose your registered email address or phone number for account recovery."}</p><form onSubmit={e=>{e.preventDefault();setNotice(reset&&password!==confirm?"Passwords do not match.":"The form is ready for the admin authentication service. Nothing has been sent or changed.");}}>
  {!login&&!reset&&<fieldset><legend>Recovery method</legend><div className="admin-auth-methods"><button type="button" aria-pressed={method==="email"} onClick={()=>{setMethod("email");setNotice("");}}>Send via Email</button><button type="button" aria-pressed={method==="sms"} onClick={()=>{setMethod("sms");setNotice("");}}>Send via SMS</button></div></fieldset>}
  {!reset&&<label>{login||method==="email"?"Email Address":"Phone Number"}<input key={method} type={login||method==="email"?"email":"tel"} autoComplete={login||method==="email"?"email":"tel"} placeholder={login?"admin@farmtry.com":method==="email"?"you@company.com":"Your registered phone number"} required/></label>}
  {reset&&<><label>Verification code (6 digits)<input className="admin-auth-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} required/></label><button type="button" disabled>Resend code</button></>}
  {(login||reset)&&<><label>{reset?"New Password":"Password"}<span className="admin-auth-password"><input aria-label={reset?"New Password":"Password"} type={visible?"text":"password"} autoComplete={reset?"new-password":"current-password"} required minLength={reset?8:undefined} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setVisible(!visible)} aria-pressed={visible}>{visible?"Hide":"Show"}</button></span></label>{reset&&<><div className="admin-auth-checks"><span>{password.length>=8?"✓":"○"} At least 8 characters</span><span>{/\d/.test(password)?"✓":"○"} Contains a number</span><span>{/[^A-Za-z0-9]/.test(password)?"✓":"○"} Special symbol</span></div><label>Confirm New Password<input type={visible?"text":"password"} autoComplete="new-password" required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{confirm&&<p>{confirm===password?"Passwords match":"Passwords do not match"}</p>}</>}</>}
  {login&&<div className="admin-auth-options"><label><input type="checkbox"/>Remember me</label><Link href="/preview/admin-recovery/">Forgot password?</Link></div>}<Button type="submit">Check form</Button><Button disabled>{login?"Log In":reset?"Update Password & Sign In":"Send Recovery Code"}</Button><p className="admin-auth-notice" role="status">{notice||"Preview only. Admin sign-in, verification and recovery are awaiting their API contracts."}</p>{!login&&!reset&&<Link href="/preview/admin-reset/">Preview the reset-password screen →</Link>}</form><Link className="admin-auth-preview-link" href="/preview/admin/">Explore the sample admin workspace →</Link></div></section></div></main>;
}
