"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { registerAggregator, type AggregatorRegistration } from "@/lib/farmtry/auth";
import { ActionError, CoreField, CoreShell, useCoreAction } from "./core-ui";

export function LiveAggregatorRegistration() {
  const action = useCoreAction(); const [submitted, setSubmitted] = useState(false); const [idType, setIdType] = useState<AggregatorRegistration["governmentIdType"]>("nin");
  return <CoreShell title="Join the aggregator network"><p>Register your contact details and operating zone, then verify your email.</p><Card className="core-card">{submitted ? <div role="status"><h2>Registration received</h2><p>Your registration has been confirmed by Farmtry. Verify your email to continue.</p><Link className="core-link" href="/preview/aggregator-verify">Verify email</Link></div> : <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const text = (key: string) => String(data.get(key) || "").trim(); void action.run(async () => { await registerAggregator({ fullName: text("fullName"), email: text("email"), password: String(data.get("password")), phone: text("phone"), zone: text("zone"), governmentIdType: idType, ...(text("governmentIdNumber") ? { governmentIdNumber: text("governmentIdNumber") } : {}), governmentIdPhotoUrl: text("governmentIdPhotoUrl"), guarantorPhone: text("guarantorPhone") }); setSubmitted(true); }); }}><fieldset disabled={action.busy} className="core-form-grid"><CoreField label="Full legal name" name="fullName" autoComplete="name" required /><CoreField label="Email address" name="email" type="email" autoComplete="email" required /><CoreField label="Password" name="password" type="password" minLength={8} autoComplete="new-password" required /><CoreField label="Phone number" name="phone" type="tel" autoComplete="tel" required /><CoreField label="Operating zone" name="zone" placeholder="e.g. Lagos-North" required /><label className="core-field"><span>Government ID type</span><select value={idType} onChange={event => setIdType(event.target.value as AggregatorRegistration["governmentIdType"])}><option value="nin">NIN</option><option value="drivers-license">Driver’s licence</option><option value="intl_passport">International passport</option></select></label><CoreField label={idType === "nin" ? "NIN (11 digits)" : "Government ID number (optional)"} name="governmentIdNumber" required={idType === "nin"} pattern={idType === "nin" ? "[0-9]{11}" : undefined} /><CoreField label="Government ID photo URL" name="governmentIdPhotoUrl" type="url" placeholder="https://…" required /><p className="core-muted core-wide">Photo uploads are not available yet. Use an existing secure image URL supplied for your registration; selecting a local file will not upload it.</p><CoreField label="Guarantor phone number" name="guarantorPhone" type="tel" required /><Button type="submit" className="core-primary core-wide" disabled={action.busy}>{action.busy ? "Registering…" : "Register"}</Button></fieldset></form>}<ActionError message={action.error} /></Card></CoreShell>;
}
