"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  createLog,
  fileDispute,
  getDashboard,
  getLog,
  getLogs,
  getStatus,
  type Dashboard,
  type LogInput,
  type LogList,
  type LogRecord,
  type ReviewStatus
} from "@/lib/aggregator/api";
import { logout } from "@/lib/auth/auth";
import { errorMessage, ApiError } from "@/lib/api-client";
import { ActionError, CoreField, CoreShell, useCoreAction } from "./core-ui";

function LogForm({ onCreated }: { onCreated: (log: LogRecord) => void }) {
  const action = useCoreAction(); const [location, setLocation] = useState("");
  return <Card className="core-card"><h2>Log produce or farm waste</h2><form onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const text = (key: string) => String(data.get(key) || "").trim(); void action.run(async () => { const payload: LogInput = { farmerPhone: text("farmerPhone"), pipeline: text("pipeline"), category: text("category"), weightKg: Number(text("weightKg")), condition: text("condition") as LogInput["condition"], latitude: Number(text("latitude")), longitude: Number(text("longitude")), photoUrl: text("photoUrl"), harvestedAt: new Date(text("harvestedAt")).toISOString() }; const log = await createLog(payload); form.reset(); onCreated(log); }); }}><fieldset disabled={action.busy} className="core-form-grid"><CoreField label="Farmer phone" name="farmerPhone" type="tel" required /><CoreField label="Pipeline" name="pipeline" placeholder="e.g. waste" required /><CoreField label="Category" name="category" placeholder="e.g. rice husks" required /><CoreField label="Weight (kg)" name="weightKg" type="number" min="0.01" step="any" required /><label className="core-field"><span>Condition</span><select name="condition"><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></select></label><CoreField label="Harvest time (your local time)" name="harvestedAt" type="datetime-local" required /><CoreField label="Latitude" name="latitude" type="number" min="-90" max="90" step="any" required /><CoreField label="Longitude" name="longitude" type="number" min="-180" max="180" step="any" required /><CoreField label="Produce photo URL" name="photoUrl" type="url" placeholder="https://…" required /><p className="core-muted">Enter the actual collection coordinates and an existing photo URL. File uploads are not yet available.</p><Button type="button" variant="secondary" onClick={event => { const form = event.currentTarget.form; if (!navigator.geolocation) { setLocation("Location is not supported. Enter the coordinates manually."); return; } setLocation("Requesting location…"); navigator.geolocation.getCurrentPosition(position => { if (!form) return; (form.elements.namedItem("latitude") as HTMLInputElement).value = String(position.coords.latitude); (form.elements.namedItem("longitude") as HTMLInputElement).value = String(position.coords.longitude); setLocation("Location captured. Review it before submitting."); }, () => setLocation("Location could not be obtained. Enter coordinates manually."), { timeout: 10000, enableHighAccuracy: true }); }}>Use my location</Button><Button className="core-primary" type="submit" disabled={action.busy}>{action.busy ? "Submitting…" : "Submit log"}</Button></fieldset></form><p role="status" className="core-muted">{location}</p><ActionError message={action.error} /></Card>;
}
function DisputeForm({ log }: { log: LogRecord }) {
  const action = useCoreAction(); const [result, setResult] = useState("");
  return <Card className="core-card"><h2>Report an issue with this log</h2>{result ? <p role="status">Dispute opened. Reference: {result}</p> : <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const text = (key: string) => String(data.get(key) || "").trim(); void action.run(async () => { const result = await fileDispute({ logId: log.id, reason: text("reason"), ...(text("weight") ? { reportedWeightKg: Number(text("weight")) } : {}), ...(text("notes") ? { notes: text("notes") } : {}), contactPhone: text("phone") }); setResult(result.disputeId); }); }}><fieldset disabled={action.busy}><CoreField label="Reason" name="reason" required /><CoreField label="Correct weight in kg (optional)" name="weight" type="number" min="0.01" step="any" /><label className="core-field"><span>Additional notes (optional)</span><textarea name="notes" rows={3} /></label><CoreField label="Contact phone" name="phone" type="tel" required /><Button type="submit" className="core-primary" disabled={action.busy}>{action.busy ? "Submitting…" : "File dispute"}</Button></fieldset></form>}<ActionError message={action.error} /></Card>;
}
export function AggregatorWorkspace() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [review, setReview] = useState<ReviewStatus | null>(null); const [list, setList] = useState<LogList | null>(null); const [selected, setSelected] = useState<LogRecord | null>(null);
  const [view, setView] = useState<"dashboard" | "logs" | "create" | "status" | "detail">("dashboard"); const [filters, setFilters] = useState({ page: 1, status: "", category: "", pipeline: "" }); const [revision, setRevision] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [authNeeded, setAuthNeeded] = useState(false); const [created, setCreated] = useState(false); const action = useCoreAction();
  useEffect(() => { const controller = new AbortController(); let active = true; setLoading(true); setError(""); setAuthNeeded(false);
    async function load() { try { if (view === "dashboard" || view === "create") { setDashboard(null); const data = await getDashboard(controller.signal); if (active) setDashboard(data); } else if (view === "logs") { setList(null); const data = await getLogs(filters, controller.signal); if (active) setList(data); } else if (view === "status") { setReview(null); const data = await getStatus(controller.signal); if (active) setReview(data); } } catch (err) { if (active) { setError(errorMessage(err)); setAuthNeeded(err instanceof ApiError && err.status === 401); } } finally { if (active) setLoading(false); } }
    if (view !== "detail") void load(); else setLoading(false);
    return () => { active = false; controller.abort(); };
  }, [view, filters, revision]);
  const openLog = (id: string) => void action.run(async () => { const log = await getLog(id); setSelected(log); setCreated(false); setView("detail"); });
  const logCards = (logs: LogRecord[]) => logs.length ? <div className="core-log-list">{logs.map(log => <button key={log.id} disabled={action.busy} onClick={() => openLog(log.id)}><span><strong>{log.category}</strong><small>{log.pipeline} · {new Date(log.createdAt).toLocaleString()}</small></span><span>{log.weightKg.toLocaleString()} kg <small>{log.status}</small></span></button>)}</div> : <p>No logs found.</p>;
  return <CoreShell title="Aggregator workspace"><div className="core-toolbar"><nav aria-label="Aggregator workspace">{([['dashboard', 'Overview'], ['logs', 'Logs'], ['create', 'New log'], ['status', 'Verification']] as const).map(([key, label]) => <Button variant={view === key ? "primary" : "secondary"} onClick={() => { setView(key); setSelected(null); }} key={key}>{label}</Button>)}</nav><Button disabled={action.busy} variant="secondary" onClick={() => void action.run(async () => { await logout(); setDashboard(null); setList(null); setReview(null); setSelected(null); window.location.assign("/preview/aggregator-login/"); })}>Sign out</Button></div><ActionError message={action.error} />
    {loading && <p role="status">Loading your records…</p>}{error && <Card className="core-card"><ActionError message={error} /><Button onClick={() => setRevision(value => value + 1)}>Try again</Button>{authNeeded && <Link className="core-link" href="/preview/aggregator-login">Sign in</Link>}</Card>}
    {!loading && !error && view === "dashboard" && dashboard && <><Card className="core-card"><h2>{dashboard.profile.fullName}</h2><p>{dashboard.profile.zone} · {dashboard.profile.email}</p><p>Identity verification: <strong>{dashboard.profile.kycStatus}</strong></p></Card><div className="core-stats">{Object.entries({ "Total logs": dashboard.stats.totalLogs, "Pending logs": dashboard.stats.pendingLogs, "Verified logs": dashboard.stats.verifiedLogs, "Total weight (kg)": dashboard.stats.totalWeightKg, "Open disputes": dashboard.stats.openDisputes }).map(([label, value]) => <Card className="core-card" key={label}><p>{label}</p><strong>{value.toLocaleString()}</strong></Card>)}</div><Card className="core-card"><h2>Recent logs</h2>{logCards(dashboard.recentLogs)}</Card></>}
    {view === "logs" && <Card className="core-card"><h2>Your logs</h2><form className="core-filters" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); setFilters({ page: 1, status: String(data.get("status") || ""), pipeline: String(data.get("pipeline") || "").trim(), category: String(data.get("category") || "").trim() }); }}><label className="core-field"><span>Status</span><select name="status" defaultValue={filters.status}><option value="">All</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label><CoreField label="Pipeline" name="pipeline" defaultValue={filters.pipeline} /><CoreField label="Category" name="category" defaultValue={filters.category} /><Button type="submit" disabled={loading}>Apply filters</Button></form>{!loading && !error && list && <>{logCards(list.logs)}<div className="core-pagination"><Button variant="secondary" disabled={list.page <= 1} onClick={() => setFilters(current => ({ ...current, page: current.page - 1 }))}>Previous</Button><span>Page {list.page} · {list.total} logs</span><Button variant="secondary" disabled={list.page * list.limit >= list.total} onClick={() => setFilters(current => ({ ...current, page: current.page + 1 }))}>Next</Button></div></>}</Card>}
    {!loading && !error && view === "status" && review && <Card className="core-card"><h2>Identity verification: {review.kycStatus}</h2>{review.rejectionReason && <p>{review.rejectionReason}</p>}<ul>{review.reviewSteps.map((step, index) => <li key={index}>{step.done ? "✓" : "○"} {step.label}</li>)}</ul></Card>}
    {!loading && !error && view === "create" && dashboard && (dashboard.profile.kycStatus === "approved" ? <LogForm onCreated={log => { setSelected(log); setCreated(true); setView("detail"); }} /> : <Card className="core-card"><h2>Identity approval required</h2><p>Your status is {dashboard.profile.kycStatus}. Produce logs can be submitted once your identity is approved.</p><Button onClick={() => setView("status")}>View review progress</Button></Card>)}
    {view === "detail" && selected && <><Card className="core-card">{created && <p role="status" className="core-success">Log submitted and confirmed by Farmtry.</p>}<h2>{selected.category}</h2><dl className="core-details">{Object.entries({ Reference: selected.id, Status: selected.status, Pipeline: selected.pipeline, "Farmer phone": selected.farmerPhone, Weight: `${selected.weightKg} kg`, Condition: selected.condition, Urgency: selected.urgencyTier, Harvested: new Date(selected.harvestedAt).toLocaleString(), Coordinates: `${selected.latitude}, ${selected.longitude}`, "Photo URL": selected.photoUrl, "QR ticket reference": selected.qrPayload }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Card><DisputeForm key={selected.id} log={selected} /></>}
  </CoreShell>;
}
