"use client";

import Link from "next/link";
import { useRef, useState, type KeyboardEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { CommerceIcon, CommerceShell } from "./commerce-shell";

// Illustrative Figma content only. These identifiers must never be sent to a service.
const sampleOffers = [
  { name: "Aminah Yusuf (Oke Ogun Hub)", detail: "In stock • Cold Refrig Van (18h SLA) • Grade A", price: 20000 },
  { name: "Adeola Agro-Allied", detail: "In stock • Ventilated Cargo (24h SLA) • Grade A−", price: 19400 },
  { name: "Maxim Agro Logistics", detail: "In stock • Express Van (12h SLA) • Grade A Premium", price: 21200 }
] as const;
const money = (value: number) => `₦ ${value.toLocaleString("en-NG")}`;
const tabLabels = ["Product Description", "Highlights & Specifications", "Shipping & Spoilage Guarantee"];
const shortLabels = ["Description", "Specifications", "Guarantee"];

function CheckItem({ children }: { children: React.ReactNode }) {
  return <li><CommerceIcon file="c861a" mobile="4ef54" />{children}</li>;
}

export function ProductPage() {
  const [quantity, setQuantity] = useState(1);
  const [offer, setOffer] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [tab, setTab] = useState(0);
  const tabs = useRef<(HTMLButtonElement | null)[]>([]);
  const selected = sampleOffers[offer];
  function navigateTab(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    const target = event.key === "ArrowRight" ? (index + 1) % 3 : event.key === "ArrowLeft" ? (index + 2) % 3 : event.key === "Home" ? 0 : event.key === "End" ? 2 : null;
    if (target !== null) { event.preventDefault(); setTab(target); tabs.current[target]?.focus(); }
  }
  return <CommerceShell><main className="commerce-width commerce-product">
    <nav className="commerce-breadcrumb" aria-label="Breadcrumb"><Link href="/preview/marketplace">Marketplace</Link><span>/</span><Link href="/preview/marketplace">Fresh Produce</Link><span>/</span><span>Tomatoes &amp; Peppers</span><span>/</span><strong>Fresh Roma Tomatoes</strong></nav>
    <div className="commerce-product-grid"><div className="commerce-gallery-column"><Card className="commerce-gallery"><div className="commerce-photo"><img src="/figma/commerce/22d63.png" alt="Fresh red tomatoes packed in ventilated crates" /><span className="commerce-desktop">Farmtry</span></div></Card><div className="commerce-guarantee"><span><CommerceIcon file="86c75" mobile="eba8b" /></span><div><h2>100% Quality &amp; Spoilage Guarantee</h2><p>Full refund or instant re-delivery if any crate does not meet fresh grade standards upon offloading.</p><small>Illustrative policy — awaiting approved terms.</small></div></div></div>
    <div className="commerce-details-column"><Card className="commerce-product-info"><h1>Fresh Tomatoes (Grade A - Premium Ripe) – Direct Gate Sourced</h1><div className="commerce-product-tags"><span>New · Be first to review</span><span>•</span><span>Lot: FT-TM-4410</span><strong><i className="commerce-mobile"><CommerceIcon file="50aa7" /></i>Grade A Verified</strong></div>
      <p className="commerce-description">Harvested fresh from certified northern farms and crated at peak ripeness. Perfectly sorted, washed, and refrigerated for wholesale buyers, restaurants, food processors, and caterers who demand consistent grade and long shelf life. <button aria-expanded={expanded} aria-controls="product-extra-description" onClick={() => setExpanded(!expanded)}>{expanded ? "Show less" : "Show more"}</button></p><p id="product-extra-description" hidden={!expanded} className="commerce-description">The sample lot is packed in ventilated 50 kg crates. Review the sample specifications and supplier offers below. Live grading, origin and availability will be confirmed when catalogue services are connected.</p>
      <dl className="commerce-specs"><div><dt>Product ID <CommerceIcon file="f00a4" mobile="2beb2" /></dt><dd>391 <i className="commerce-mobile"><CommerceIcon file="2beb2" /></i></dd></div><div><dt>Aggregator <CommerceIcon file="f00a4" mobile="2beb2" /></dt><dd>Amina <i className="commerce-mobile"><CommerceIcon file="2beb2" /></i></dd></div><div><dt>Origin / Hub</dt><dd>Oke Ogun</dd></div><div><dt>Category</dt><dd>Fresh Vegetables</dd></div><div><dt>Availability</dt><dd><span>In stock (140 crates available)</span></dd></div></dl>
      <div className="commerce-purchase"><p className="commerce-price"><strong>{money(selected.price)}</strong><small>(50 kg crate · sample landed cost)</small></p><div className="commerce-purchase-actions"><div className="commerce-quantity" role="group" aria-label="Sample quantity"><button aria-label="Decrease quantity" disabled={quantity === 1} onClick={() => setQuantity(q => q - 1)}><span className="commerce-desktop"><CommerceIcon file="d7fe7" /></span><span className="commerce-mobile">−</span></button><output aria-live="polite" aria-label="Quantity">{quantity}</output><button aria-label="Increase quantity" disabled={quantity === 140} onClick={() => setQuantity(q => q + 1)}>+</button></div><Button className="commerce-add" disabled aria-describedby="purchase-unavailable"><span>Add to Cart</span><CommerceIcon file="fc0d7" /></Button><Button variant="secondary" className="commerce-buy" disabled aria-describedby="purchase-unavailable">Buy now</Button></div><p id="purchase-unavailable" className="commerce-unavailable">Purchases are unavailable in this preview. Quantity and offer choices stay on this page.</p></div>
      <div className="commerce-secondary-actions"><div><button disabled><CommerceIcon file="7290a" mobile="a9a59" />Wishlist</button><button disabled><CommerceIcon file="b357b" mobile="1b5ab" />Request callback</button></div><div><span>Share</span><button disabled aria-label="Copy product link"><CommerceIcon file="3432a" mobile="f00a4" /></button><button disabled className="commerce-desktop" aria-label="Share on X"><CommerceIcon file="76ca9" /></button><button disabled className="commerce-desktop" aria-label="Share on Facebook"><CommerceIcon file="02b22" /></button><button disabled aria-label="Share on WhatsApp"><span className="commerce-desktop"><CommerceIcon file="ed6cb" /></span><span className="commerce-mobile">WA</span></button></div></div>
    </Card>
    <Card className="commerce-sla"><h2><span><i className="commerce-desktop"><CommerceIcon file="9f280" /></i><span className="commerce-mobile">⚡</span>18-Hour Fresh Delivery SLA</span><small>Active Cold-Chain</small></h2><div><p><span>Next Departure Window</span><strong>Today @ 4:30 PM</strong></p><p><span>Guaranteed Doorstep Arrival</span><strong>Tomorrow, 8:00 AM</strong></p></div><p className="commerce-unavailable">Sample schedule for Aminah’s offer; no live delivery quote.</p></Card>
    <Card className="commerce-breakdown"><h2>Price breakdown</h2>{offer === 0 ? <dl><div><dt>Produce Cost (50kg @ ₦310/kg)</dt><dd>{money(15500 * quantity)}</dd></div><div><dt>Temperature-Controlled Dispatch &amp; Delivery</dt><dd>{money(4000 * quantity)}</dd></div><div><dt>Vented Plastic Crate Deposit (Refundable upon return)</dt><dd>{money(500 * quantity)}</dd></div></dl> : <p className="commerce-unavailable">This sample offer does not include an itemised breakdown. An approved quote will be required.</p>}<p className="commerce-total"><strong>Sample total · {quantity} {quantity === 1 ? "crate" : "crates"}</strong><strong>{money(selected.price * quantity)}</strong></p><p className="commerce-unavailable">Illustrative arithmetic only; delivery is not a confirmed quote.</p></Card>
    <Card className="commerce-offers"><h2>Other Aggregators on Farmtry</h2><p>Compare sample price, stock, and fulfilment before you buy.</p><div role="group" aria-label="Compare sample supplier offers">{sampleOffers.map((item, index) => <div className={`commerce-offer ${offer === index ? "is-selected" : ""}`} key={item.name}><div><h3>{item.name}</h3><p>{item.detail}</p></div><strong>{money(item.price)}</strong><Button aria-pressed={offer === index} aria-label={`Compare offer from ${item.name}`} onClick={() => setOffer(index)}>{offer === index ? "Selected" : "Select offer"}</Button></div>)}</div><p className="commerce-unavailable" role="status">Comparing: {selected.name}. No offer has been reserved.</p></Card></div></div>
    <Card className="commerce-product-tabs"><div role="tablist" aria-label="Product information">{tabLabels.map((label, index) => <button key={label} ref={element => { tabs.current[index] = element; }} role="tab" id={`product-tab-${index}`} aria-controls={`product-panel-${index}`} aria-selected={tab === index} tabIndex={tab === index ? 0 : -1} onKeyDown={event => navigateTab(event, index)} onClick={() => setTab(index)}><span className="commerce-desktop">{label}</span><span className="commerce-mobile">{shortLabels[index]}</span></button>)}</div>
      <div role="tabpanel" id="product-panel-0" aria-labelledby="product-tab-0" hidden={tab !== 0} tabIndex={0}><div className="commerce-tab-columns"><section><h2>Freshness standard</h2><p>Grown under direct agro-guidance in Kaduna and carefully sorted by hand and mechanical grader. All crates are inspected to ensure only firm, ripe, unbruised Roma tomatoes are packed.</p><ul><CheckItem>Grade: Premium Grade A (Plum Variety)</CheckItem><CheckItem>Weight: 50.0 kg net weight per crate</CheckItem></ul></section><section><h2>Packaging &amp; storage</h2><p>Delivered in ventilated plastic crates that shield produce from road compression and maintain airflow during transit.</p><ul><CheckItem>Shelf Life: 7–10 days in standard cool conditions</CheckItem><CheckItem>Crate Deposit: ₦500 refundable upon return</CheckItem></ul></section><section><h2>Buyer protection</h2><p>Sample policy: every consignment is covered by Farmtry’s Spoilage Guarantee. Drivers wait while your team inspects produce off-loading.</p><Link className="commerce-help" href="/preview/support"><strong>Need Help or Custom Volume?</strong><span>Speak with our Agro Sourcing Desk</span></Link></section></div></div>
      <div role="tabpanel" id="product-panel-1" aria-labelledby="product-tab-1" hidden={tab !== 1} tabIndex={0}><h2>Highlights &amp; specifications</h2><dl className="commerce-specs"><div><dt>Variety</dt><dd>Premium Grade A Plum</dd></div><div><dt>Net weight</dt><dd>50.0 kg per crate</dd></div><div><dt>Packaging</dt><dd>Ventilated plastic crates</dd></div><div><dt>Sample shelf life</dt><dd>7–10 days in cool conditions</dd></div></dl><p className="commerce-unavailable">These are design samples. The final product record and quality certificate will supply verified specifications.</p></div>
      <div role="tabpanel" id="product-panel-2" aria-labelledby="product-tab-2" hidden={tab !== 2} tabIndex={0}><h2>Shipping &amp; spoilage guarantee</h2><p>Sample delivery uses temperature-controlled dispatch and inspection during off-loading. The reference policy offers a refund or re-delivery for crates that fail fresh grade standards.</p><p className="commerce-unavailable">Coverage, eligibility, claim deadlines, crate returns and delivery timing await approved service terms. This preview makes no delivery or refund commitment.</p><Link className="commerce-help" href="/preview/governance">View governance and trust</Link></div>
    </Card>
  </main></CommerceShell>;
}
