'use client';
import Link from 'next/link';
import {cloneElement,isValidElement,useId,type ReactElement,type ReactNode} from 'react';
import { Button } from '@/components/ui/button';
export const aggUrl = (page: string) => '/preview/aggregator-' + page + '/';
export function DesignImage({screen,id,alt='',className=''}:{screen:string;id:string;alt?:string;className?:string}) {return <img className={className} src={`/figma/native/${screen}/${id}.svg`} alt={alt} />;}
export function DesignLink({to,children,secondary=false}:{to:string;children:ReactNode;secondary?:boolean}) {return <Link className={'agg-button'+(secondary?' agg-secondary':'')} href={aggUrl(to)}>{children}</Link>;}
export function ServiceButton({children}:{children:ReactNode}) {return <Button disabled title="This service is not connected in the design preview." className="agg-button">{children}</Button>;}
export function DesignShell({title,children,active='Home',back='home-design',nav=true}:{title:string;children:ReactNode;active?:string;back?:string;nav?:boolean}) {const items=[['Home','home-design','295-9016'],['Verifications','verifications','295-9021'],['Matches','matches','295-9026'],['Earnings','earnings','295-9031']];return <div className="agg-design"><div className="agg-canvas"><header className="agg-header"><Link aria-label="Back to aggregator preview" href={aggUrl(back)}>←</Link><h1>{title}</h1><Link className="agg-live" href="/preview/aggregator/">Live workspace</Link></header><p className="agg-notice">Design preview · Sample records. No account, payment or verification is submitted.</p><main className="agg-main">{children}</main>{nav&&<nav className="agg-nav" aria-label="Aggregator navigation">{items.map(([label,page,icon])=><Link key={page} href={aggUrl(page)} aria-current={active===label?'page':undefined}><DesignImage screen="295-8750" id={icon}/><span>{label}</span></Link>)}<Link href="/aggregator/profile/"><DesignImage screen="295-8750" id="295-9036"/><span>Profile</span></Link></nav>}</div></div>;}
export function Steps({step}:{step:number}) {return <div className="agg-steps" aria-label={`Step ${step} of 4`}><ol>{[1,2,3,4].map(i=><li key={i} className={i<=step?'active':''} aria-current={i===step?'step':undefined}>{i<step?'✓':i}</li>)}</ol><p>Step {step} of 4</p></div>;}
export function Field({label,children}:{label:string;children:ReactNode}){const id=useId();const direct=isValidElement(children)&&typeof children.type==='string'&&['input','select','textarea'].includes(children.type);return <div className="agg-field">{direct?<label htmlFor={id}>{label}</label>:<span>{label}</span>}{direct?cloneElement(children as ReactElement<{id?:string}>,{id}):children}</div>;}
export function SampleSuccess({title,children}:{title:string;children:ReactNode}){return <div className="agg-success"><div className="agg-check" aria-hidden="true">✓</div><h2>{title}</h2><p className="agg-caption">Saved success-state example · No action has been completed.</p>{children}</div>;}
