import type {AggregatorDesignPage} from './aggregator-design-data';
import {AggregatorHomeDesign,AggregatorOverview,AggregatorVerifications,AggregatorFarmers,AggregatorFarmerDetail,AggregatorVerifiedHistory} from './aggregator-directory';
import {AddFarmerIntro,FarmerRegistration,FarmerRegistrationExample,VerificationFlow,VerificationExample} from './aggregator-forms';
import {AggregatorEarnings,AggregatorMatches,AggregatorMatchInformation,AggregatorDeliveryTicket} from './aggregator-fulfillment';
import {AggregatorIntro,AggregatorSplash,AggregatorRegistrationDesign,AggregatorAccountDesign} from './aggregator-account';
export function AggregatorDesignPageView({page}:{page:AggregatorDesignPage}){const view=page.replace('aggregator-','');
 switch(view){
 case 'start':return <AggregatorSplash/>;
 case 'intro':return <AggregatorIntro/>;
 case 'intro-payouts':return <AggregatorIntro initial={1}/>;
 case 'intro-tickets':return <AggregatorIntro initial={2}/>;
 case 'register-design':return <AggregatorRegistrationDesign/>;
 case 'login-design':return <AggregatorAccountDesign view="login"/>;
 case 'recovery-design':return <AggregatorAccountDesign view="recovery"/>;
 case 'recovery-sms-design':return <AggregatorAccountDesign view="recovery-sms"/>;
 case 'reset-design':return <AggregatorAccountDesign view="reset"/>;
 case 'reset-code-design':return <AggregatorAccountDesign view="code"/>;
 case 'reset-sent-design':return <AggregatorAccountDesign view="sent"/>;
 case 'verification-success':return <AggregatorAccountDesign view="success"/>;
 case 'verification-failed':return <AggregatorAccountDesign view="failed"/>;
 case 'phone-verification':return <AggregatorAccountDesign view="phone"/>;
 case 'home-operations':return <AggregatorHomeDesign operations/>;
 case 'home-overview':return <AggregatorOverview/>;
 case 'match-confirmed':return <AggregatorMatchInformation stage="confirmed"/>;
 case 'match-corridor':return <AggregatorMatchInformation stage="corridor"/>;
 case 'home-design':return <AggregatorHomeDesign/>;
 case 'verifications':return <AggregatorVerifications/>;
 case 'verifications-fresh':return <AggregatorVerifications initial="fresh"/>;
 case 'verifications-waste':return <AggregatorVerifications initial="waste"/>;
 case 'verified-history':return <AggregatorVerifiedHistory/>;
 case 'verified-waste':return <AggregatorVerifiedHistory waste/>;
 case 'verify-produce':return <VerificationFlow/>;
 case 'verify-waste':return <VerificationFlow waste/>;
 case 'log-produce-design':return <VerificationFlow log/>;
 case 'log-waste-design':return <VerificationFlow log waste/>;
 case 'photos':return <VerificationFlow initialStep={2}/>;
 case 'review':return <VerificationFlow initialStep={3}/>;
 case 'review-confirmed':return <VerificationFlow initialStep={3} confirmed/>;
 case 'submission-example':return <VerificationExample/>;
 case 'farmers':return <AggregatorFarmers/>;
 case 'farmers-verified':return <AggregatorFarmers initial="Verified"/>;
 case 'farmers-pending':return <AggregatorFarmers initial="Pending"/>;
 case 'farmer-detail':return <AggregatorFarmerDetail/>;
 case 'add-farmer':return <AddFarmerIntro/>;
 case 'farmer-information':return <FarmerRegistration/>;
 case 'farmer-location':return <FarmerRegistration initialStep={2}/>;
 case 'farmer-crops':return <FarmerRegistration initialStep={3}/>;
 case 'farmer-produce':return <FarmerRegistration initialStep={4}/>;
 case 'registration-example':return <FarmerRegistrationExample/>;
 case 'earnings':return <AggregatorEarnings/>;
 case 'withdrawal':return <AggregatorEarnings view="withdrawal"/>;
 case 'withdrawal-example':return <AggregatorEarnings view="success"/>;
 case 'matches':return <AggregatorMatches/>;
 case 'match-history':return <AggregatorMatches history/>;
 case 'match-information':return <AggregatorMatchInformation/>;
 case 'handover':return <AggregatorMatchInformation stage="handover"/>;
 case 'delivery-complete':return <AggregatorMatchInformation stage="complete"/>;
 case 'transit':return <AggregatorMatchInformation stage="transit"/>;
 case 'delivery-ticket':return <AggregatorDeliveryTicket/>;
 default:return null;
 }
}
