"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { BuyerShell, Icon } from "./buyer-shell";

const listings=[
  {name:"Maize Husks",image:"96969.png",type:"Fresh Produce",quality:"Waste Grade A • Raw",distance:2.5,price:340000,weight:"800 kg"},
  {name:"Cassava Peels",image:"559f9.png",type:"Farm Waste",quality:"Grade B • Dry",distance:4.2,price:180000,weight:"600 kg"},
  {name:"Tomatoes",image:"72b9f.png",type:"Fresh Produce",quality:"Grade A • Fresh",distance:6.8,price:520000,weight:"1,200 kg"},
  {name:"Yellow Maize",image:"89067.png",type:"Fresh Produce",quality:"Grade A • Dry",distance:7.1,price:620000,weight:"1,000 kg"},
];
const money=(amount:number)=>`₦${amount.toLocaleString("en-NG")}`;
export function BuyerListings(){
  const [filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[sort,setSort]=useState("design");
  const items=listings.filter(item=>(filter==="All"||item.type===filter)&&`${item.name} ${item.quality} Oyo State`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:listings.indexOf(a)-listings.indexOf(b));
  return <BuyerShell screen="listings" onSearch={setQuery}><div className="buyer-work-title"><div><h1>Available Listings</h1><p role="status">{items.length} sample results{query&&` for “${query}”`}</p></div><label className="buyer-listing-sort">Sort by:<span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="design">Design order</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select><Icon screen="listings" file="37db4"/></span></label></div><div className="buyer-notification-filters buyer-listing-filters" role="group" aria-label="Filter sample listings">{["All","Fresh Produce","Farm Waste"].map(value=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div><p className="buyer-work-service-note"><Link href="/preview/buyer-filtered-listings/">Browse crops &amp; waste with detailed filters →</Link></p><div className="buyer-listing-list">{items.map(item=><Card className="buyer-listing-card" key={item.name}><div className="buyer-listing-photo"><img src={`/figma/buyer-workspace/329-2673/${item.image}`} alt={item.name}/></div><div className="buyer-listing-description"><h2>{item.name}<small className={item.type==="Farm Waste"?"waste":""}>{item.type==="Farm Waste"?"Agri-Waste":item.type}</small></h2><p>{item.quality}</p><p><Icon screen="listings" file="f7acd"/>Oyo State • {item.distance} km</p><div><strong>{money(item.price)}</strong><span>{item.weight} available</span></div></div><div className="buyer-listing-actions"><button disabled aria-label={`Save ${item.name}`} title="Saved listings API unavailable"><Icon screen="listings" file="b2197"/></button>{item.name==="Maize Husks"?<Link href="/preview/buyer-listing" className="buyer-green-link">View Details</Link>:<Button disabled title="This listing detail reference is not available">View Details</Button>}</div></Card>)}{!items.length&&<Card className="buyer-order-empty"><h2>No matching sample listings</h2><p>Try another search or clear the filters.</p><Button variant="secondary" onClick={()=>{setQuery("");setFilter("All");}}>Reset filters</Button></Card>}</div><p className="buyer-work-service-note">Only the four saved design examples are shown. Prices, stock, distances and categories are illustrative; live catalogue and saved items await their API contracts.</p></BuyerShell>;
}

export function BuyerListingDetail(){return <BuyerShell screen="listing"><div className="buyer-detail-width"><div className="buyer-detail-toolbar"><Link href="/preview/buyer-listings"><Icon screen="listing" file="ba314"/>Listing Details</Link><div><button disabled aria-label="Save listing"><Icon screen="listing" file="cccee"/></button><button disabled aria-label="Share listing"><Icon screen="listing" file="76329"/></button></div></div><Card className="buyer-listing-detail"><div className="buyer-detail-hero"><img src="/figma/buyer-workspace/329-2986/070a6.png" alt="Maize husks in bulk dry storage"/><span>1 saved image</span></div><div className="buyer-detail-content"><div className="buyer-detail-heading"><div><h1>Maize Husks <small>Fresh Produce</small></h1><p>Waste Grade A • Raw</p></div><div><strong>₦340,000</strong><p>800 kg available</p></div></div><div className="buyer-detail-facts"><div><Icon screen="listing" file="a88ad"/><p><small>Location</small>Oyo State <span>• 2.5 km</span></p></div><div><Icon screen="listing" file="af175"/><p><small>Farmer</small>Adewale Farms</p><span className="buyer-quality-badge"><Icon screen="listing" file="7617d"/>Verified</span></div></div><section className="buyer-detail-section"><h2>Quality Details</h2><div className="buyer-quality-tags"><span><Icon screen="listing" file="623c0"/>Good Quality</span><span><Icon screen="listing" file="b93c7"/>Low Moisture</span><span>Grade A</span></div></section><section className="buyer-detail-section"><h2>Description</h2><p>Clean maize husks, suitable for biofuel production, animal feed, or industrial processing. Directly harvested and stored in dry conditions to preserve fiber integrity and ensure zero mold contamination.</p></section><div className="buyer-detail-match"><div><h2>● Match with this listing</h2><p>1 buyer match available according to your corporate procurement criteria</p></div><Link href="/preview/buyer-match" className="buyer-green-link"><Icon screen="listing" file="2a2b0"/>View Match Details</Link></div><div className="buyer-detail-buttons"><Button variant="secondary" disabled><Icon screen="listing" file="c5f54"/>Save</Button><Button disabled><Icon screen="listing" file="f7771"/>Contact Supplier</Button></div><p className="buyer-work-service-note">Quality and matching information are sample design content. Saving and supplier contact await backend contracts.</p></div></Card></div></BuyerShell>;}

export function BuyerMatchDetail(){const [open,setOpen]=useState(true),[options,setOptions]=useState(false);return <BuyerShell screen="match"><div className="buyer-match-width"><div className="buyer-detail-toolbar"><Link href="/preview/buyer-listing"><Icon screen="match" file="e7429"/><h1>Match Details</h1></Link><button aria-label="Match options" aria-expanded={options} onClick={()=>setOptions(!options)}><Icon screen="match" file="bdb02"/></button></div>{options&&<p className="buyer-notification-options" role="status">Match actions are unavailable until the buyer API is connected. This is a saved example.</p>}<Card className="buyer-match-detail"><div className="buyer-match-product"><div className="buyer-listing-photo"><img src="/figma/buyer-workspace/329-3178/cdcdb.png" alt="Maize husks"/></div><div><h2>Maize Husks <small>Fresh Produce</small></h2><p>Waste Grade A • Raw</p><strong>₦340,000</strong></div><div className="buyer-match-state"><span><Icon screen="match" file="9f382"/>Match Confirmed · sample</span><small>800 kg total</small></div></div><div className="buyer-match-company"><span className="buyer-match-company-icon"><Icon screen="match" file="5c5d2"/></span><div><h2>ABC Foods Ltd <Icon screen="match" file="a6e0a"/></h2><p>Corporate Buyer • Certified Hub Member</p></div><span className="buyer-match-rating"><Icon screen="match" file="86ca2"/>4.8 <small>(120 completed)</small></span></div><div className="buyer-match-fact"><Icon screen="match" file="8ed67"/><div><h2>Pickup Schedule</h2><strong>Aug 26, 2026 • 10:00 AM – 12:00 PM</strong><p>Confirmed by Hub Coordinator</p></div></div><div className="buyer-match-fact"><Icon screen="match" file="245b7"/><div><h2>Pickup Location</h2><strong>Oyo, Ibadan Farm Hub</strong><p>Plot 42, Agricultural Zone C, Ibadan North</p></div></div><section className="buyer-match-summary"><button aria-expanded={open} aria-controls="buyer-match-costs" onClick={()=>setOpen(!open)}><span><Icon screen="match" file="dab2a"/>Order Summary</span><Icon screen="match" file="754f1"/></button>{open&&<dl id="buyer-match-costs"><div><dt>Produce Cost (800 kg @ ₦425/kg)</dt><dd>₦340,000</dd></div><div><dt>Logistics &amp; Handling Fee</dt><dd>₦12,500</dd></div><div><dt>Platform Service</dt><dd>₦3,400</dd></div><div className="buyer-match-total"><dt>Total Payable</dt><dd>₦355,900</dd></div></dl>}</section><div className="buyer-detail-buttons"><Button variant="secondary" disabled>Decline</Button><Button disabled>Accept Match<Icon screen="match" file="6a46a"/></Button></div><p className="buyer-work-service-note">No match has been accepted or declined. The illustrated status, schedule and charges are not a live booking.</p></Card></div></BuyerShell>;}

export function BuyerScanner(){const [manual,setManual]=useState(false),[code,setCode]=useState(""),[help,setHelp]=useState(false);return <BuyerShell screen="scan"><div className="buyer-scan-width"><div className="buyer-work-title"><div className="buyer-scan-heading"><Link href="/preview/buyer" aria-label="Back to buyer dashboard"><Icon screen="scan" file="40550"/></Link><div><h1>Scan QR Code</h1><p>Direct Verification &amp; Instant Intake Reception</p></div></div><span className="buyer-scan-hub">● Sample Intake Hub: <strong>Oyo Farm Hub #3</strong></span></div><Card className="buyer-scan-panel"><div className="buyer-scan-camera"><div className="buyer-scan-tools"><button disabled aria-label="Toggle camera flash"><Icon screen="scan" file="e4132"/></button><button disabled aria-label="Switch camera"><Icon screen="scan" file="9c60e"/></button></div><div className="buyer-scan-target"><i/><i/><i/><i/><div><Icon screen="scan" file="73083"/></div><span/></div><p>Scan the buyer or seller QR code at the collection point</p><small>Design example only · camera and verification are unavailable</small><Button onClick={()=>setManual(!manual)} aria-expanded={manual} aria-controls="buyer-manual-code"><Icon screen="scan" file="fd533"/>{manual?"Hide manual entry":"Enter Code Manually"}</Button>{manual&&<div id="buyer-manual-code" className="buyer-manual-code"><label htmlFor="buyer-code">Batch or handover reference</label><input id="buyer-code" value={code} onChange={event=>setCode(event.target.value)} placeholder="Enter the reference" maxLength={128}/><Button disabled>Verify code</Button><p>No code is submitted or checked in this preview.</p></div>}</div><div className="buyer-scan-caption"><span><Icon screen="scan" file="368da"/>Preview only · no cryptographic check performed</span><div><button disabled>Camera Settings</button><span>•</span><button aria-expanded={help} onClick={()=>setHelp(!help)}>Troubleshooting</button></div></div></Card>{help&&<p className="buyer-notification-options" role="status">This screen is a design preview. Camera access, QR validation and receipt confirmation need the backend contract. You can inspect the manual-entry layout without granting camera access.</p>}<Card className="buyer-scan-batch"><div><h2>● Sample batch on terminal</h2><span>Intake Ready · sample</span></div><div className="buyer-scan-batch-detail"><span>LOT-41</span><div><h3>Maize Husks (Waste Grade A - Raw)</h3><p>Seller: Adewale Farms Ltd • Hub: Oyo Agricultural Zone C</p></div><div><strong>800 kg</strong><p>₦340,000</p></div><Button disabled>Confirm Handover</Button></div></Card><p className="buyer-work-service-note">The QR graphic and batch are saved design examples. No delivery, receipt or handover has been verified.</p></div></BuyerShell>;}
